# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_location_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='register_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
