# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_location_register_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_latitude', models.FloatField()),
                ('restaurant_longitude', models.FloatField()),
                ('restaurant_name', models.CharField(max_length=20)),
                ('restaurant_id', models.IntegerField()),
            ],
        ),
    ]
