# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='member_id',
            field=models.IntegerField(default=0),
        ),
    ]
