# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170822_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='restaurant_address',
            field=models.CharField(default='', max_length=30),
        ),
    ]
